### ISSUE TITLE
missing attributes

### ISSUE THREAD

**Issue by Metis77** [derhaeuptling/contao-immobilienscout24-import-bundle#10]
I am not sure, if those attributes are even available in live API.
But the they might be. 
@m-vo could you check?

buildingType->FARMHOUSE (Bauernhaus)
buildingType->OTHER (Sonstiges)
Lift (Aufzug)

**Comment by m-vo** [comment]
Where did you get these from?

**Comment by Metis77** [comment]
**buildingType->FARMHOUSE (Bauernhaus)
buildingType->OTHER (Sonstiges)**

In the backend of ImmoScout24 I can select those.
<img width="459" alt="building_types" src="https://user-images.githubusercontent.com/1408361/69500587-b639a500-0efc-11ea-8f8d-4da355470d94.png">



Also the value "Other" was available for all other objectTypes except of the buildingType.

And in the documentation of the API: 
https://api.immobilienscout24.de/our-apis/import-export/ftp-vs-api/house.html
I know this is the wrong API documentation, but the value can be set in the backend.


**Lift (Aufzug)**
But we can probably omit "Lift" as I can not set it in the ImmoScout24 backend.

**Comment by m-vo** [comment]
implemented in 885d496f810ce8e8928d941354f117b73e27e105
