### ISSUE TITLE
Add publishChannels

### ISSUE THREAD

**Issue by Metis77** [derhaeuptling/contao-immobilienscout24-import-bundle#16]
The import/export API contains in its Request for all or specific real estates information about where the objects should be published.
Possible values are Immobilienscout24  and/or Homepage.

The request would be the normal import API Request like:
https://rest.immobilienscout24.de/restapi/api/offer/v1.0/user/me/realestate

the part of the JSON response:
```JSON
"common.publishChannels":[
            {
              "publishChannel":[
                {
                  "@id":"10000",
                  "@title":"Immobilienscout24"
                },
                {
                  "@id":"10001",
                  "@title":"Homepage"
                }
              ]
            }
          ]
```

@m-vo is it possible to add this?

**Comment by m-vo** [comment]
In general: yes. I'd have to see if this information is really available in the actual data and has meaningful values, though (this wasn't the case for quite some of the documented values).

**Comment by Metis77** [comment]
It was available in the live playground just now ... but as far as i can recall is was not when we started this plugin.
Would be great, if you could check this.
