### ISSUE TITLE
Add API-Suchfelder 

### ISSUE THREAD

**Issue by Metis77** [derhaeuptling/contao-immobilienscout24-import-bundle#17]
Each Object can contain three individueal fields, the apiSearchData fields.

request:
https://rest.immobilienscout24.de/restapi/api/offer/v1.0/user/me/realestate/118812510

answer:
```JSON
"apiSearchData":{
      "searchField1":"API-Suchfeld1",
      "searchField2":"API-Suchfeld2",
      "searchField3":"API-Suchfeld3"
    },
```

for testing: ObjectID 118812510 does contain above data.

**Comment by m-vo** [comment]
closed via #19
