### ISSUE TITLE
Add Objektnummer & Gruppennummer

### ISSUE THREAD

**Issue by Metis77** [derhaeuptling/contao-immobilienscout24-import-bundle#18]
Each Object can contain an individual "Objektnummer" and "Gruppennummer".
Attribute names are: externalId & groupNumber

request:
https://rest.immobilienscout24.de/restapi/api/offer/v1.0/user/me/realestate/118812510

answer:
```JSON
{
  "realestates.houseBuy":{
    "@id":"118812510",
    "externalId":"119",
    "groupNumber":3
 }
}
```

**Comment by m-vo** [comment]
closed via #19
