### ISSUE TITLE
Image sizes & image template rendering

### ISSUE THREAD

**Issue by m-vo** [derhaeuptling/contao-immobilienscout24-import-bundle#2]

**Comment by m-vo** [comment]
implemented in dca7a15af38c99f605c23764693a52ab8e718a70

**Comment by Metis77** [comment]
so `alternativeImageSize` gets the original image and `defaultImageSize` the one from the module settings?

**Comment by m-vo** [comment]
No both are **size configurations** from the modules (lister only has default, because I don't think it makes sense to offer multiple here). And if you want to use 10 special ones in a template just specify them there instead of using one of the two references at all.

It's all in the README btw: https://github.com/derhaeuptling/contao-immobilienscout24-import-bundle/commit/58310c0089e9ac3c85b3facde17f885b2c7fcb43#diff-04c6e90faac2675aa89e2176d2eec7d8R101-R106
