### ISSUE TITLE
Error with RegistryInterface on doctrine/doctrine-bundle 2.*

### ISSUE THREAD

**Issue by OMOSde** [derhaeuptling/contao-immobilienscout24-import-bundle#31]
I installed the bundle in a Contao 4.9.20 (Symfony 4.4.30).

Afterwards there were error messages concerning the class RegistryInterface when creating an account.

The cause is probably a remove of a deprecation in doctrine/doctrine-bundle 2.0 (see: https://github.com/doctrine/DoctrineBundle/blob/2.3.x/UPGRADE-2.0.md).

I then made adjustments in my installation following this example (https://github.com/sonata-project/SonataPageBundle/pull/1099/files) and all problems were solved.

Best regards
René

**Comment by m-vo** [comment]
> The cause is probably a remove of a deprecation in doctrine/doctrine-bundle 2.0 (see: https://github.com/doctrine/DoctrineBundle/blob/2.3.x/UPGRADE-2.0.md).

Thanks for debugging. I think we can safely exchange the interface here, too. We should probably also add `doctrine/doctrine-bundle` to our requirements (with `^1.8 || ^2.0`).

Could you provide a PR with the needed fixes?

**Comment by Metis77** [comment]
@OMOSde 
So great you could solve this one. Would you like to offer a pull request with the fixes?

**Comment by OMOSde** [comment]
I think this is my first pull request. I hope I did everything right.

**Comment by m-vo** [comment]
Closing in favor of #32
