### ISSUE TITLE
immoscout24:scrape-attachments detect missing images

### ISSUE THREAD

**Issue by Metis77** [derhaeuptling/contao-immobilienscout24-import-bundle#38]
`immoscout24:scrape-attachments` lädt keine fehlenden Bilder nach.
Bilder werden nur geladen, wenn zuvor per `immoscout24:sync --purge`  die Datenbankeinträge UND die Bilder gelöscht wurden.

Warum ist das jetzt  auf ein Thema?
1. lokal dev
Bei lokaler Entwicklung wird, gerade am Anfang, oft die DB auf den Server gepusht.
Dabei werden aber nicht unbedingt die Bilder mit hochgeladen. Diese sollten beim nächsten `immoscout24:scrape-attachments` soweit sie fehlen, nachgeladen werden.

2. Bilder in Contao gelöscht
Auch in diesem Fall werden Bilder nicht per `immoscout24:scrape-attachments` erneut geladen.

3. Bilder werden außerhalb von Contao gelöscht
siehe #44 

Gibt es eine "gute" Lösung, das anders zu machen?

**Comment by m-vo** [comment]
Wir können das FS scannen und fehlende Bilder in der Datenbank zurücksetzen/neu scrapen.
