### ISSUE TITLE
frontend tolerate missing image

### ISSUE THREAD

**Issue by Metis77** [derhaeuptling/contao-immobilienscout24-import-bundle#44]
when deleting directly without contao:
`
request.CRITICAL: Uncaught PHP Exception Contao\Image\Exception\FileNotExistsException
`

If deleted in Contao, no problem occurs.

**Comment by m-vo** [comment]
Wir könnten:

 * Requirement auf Contao 4.13 anheben
 * attachments den Figure Builder nutzen lassen
 * Ausgabe im mitgelieferten Template anpassen

**Comment by m-vo** [comment]
See #49
