### ISSUE TITLE
Only update modified objects

### ISSUE THREAD

**Issue by Metis77** [derhaeuptling/contao-immobilienscout24-import-bundle#45]
the query 
`https://rest.immobilienscout24.de/restapi/api/offer/v1.0/user/me/realestate`

Gives an xml list of all real estates that also contains the `modification` .

This is the same as `lastModificationDate` from realEstate Query:
`https://rest.immobilienscout24.de/restapi/api/offer/v1.0/user/me/realestate/{{Scout-ID}}`

At least both values are the same by second, but differ in some number that is appended. 
Maybe milliseconds?
`2022-10-19T10:04:13.776Z` vs `2022-10-19T10:04:13.765Z`

this makes me think:
why not reading the /realestate/{{Scout-ID}} only it that {{Scout-ID}} has a newer modification date?

**Comment by m-vo** [comment]
See #49
