### ISSUE TITLE
ImmoScout Account list enable/disable icon/eye broken

### ISSUE THREAD

**Issue by Metis77** [derhaeuptling/contao-immobilienscout24-import-bundle#48]
<img width="320" alt="Bildschirm­foto 2022-10-25 um 11 24 10" src="https://user-images.githubusercontent.com/1408361/197736732-15ecf27c-83d0-41d3-83a3-8d82d24ce191.png">

Das Auge lässt sich in Contao 4.13 nicht mehr klicken.
In dein Einstellungen selber klappt es.

**Comment by m-vo** [comment]
See #49
