### ISSUE TITLE
API: Also get archived real estates

### ISSUE THREAD

**Issue by m-vo** [derhaeuptling/contao-immobilienscout24-import-bundle#5]

**Comment by m-vo** [comment]
see fefa014 - this does not make them distinguishable, though.

**Comment by Metis77** [comment]
alternatively to using the Archive feature of immoscout, we could use the api searchField1.
https://api.immobilienscout24.de/our-apis/import-export/ftp-vs-api/apartment.html

to test this, there should be two objects with searchField1 = Referenzen

**Comment by m-vo** [comment]
Again, this is a completely different API. 

Imo it's a bug (API) that `listed` isn't set, nor does the state differ.

**Comment by Metis77** [comment]
just in case this helps.
On https://api.immobilienscout24.de/useful/changelog.html I found:

> Import Export API: Status „archived“ will not be handed out anymore

> We have analyzed the usage of the status „archived“ within GET REALESTATE requests and the result is, that it is not being used. „archived“ is not connected with functionalities, it’s just a label for real estates which are deactivated over a longer period of time. Since we don’t offer archiving a real estate by API, we’ve decided to delete this attribute. Therewith, the remaining status are „active“ and „inactive“.

Yet the query parameter `archivedobjectsincluded (true/false)` still works.

**Comment by m-vo** [comment]
You might want to open an issue at Immoscout24 then. There is nothing we can do.

**Comment by Metis77** [comment]
Ok.

We could also define those objects manually in the backend by `realEstateId  == 114085263  or realEstateId  ==  114007177`.

But it would be great to have any simpler way of doing this.
Maybe simply `realEstateId  == (114085263  or 114007177)`

Optional: Or even better a list in module settings with a checkbox for this.

**Comment by m-vo** [comment]
Closing this as this issue lies within Immoscout24 and not our API implementation.
