### ISSUE TITLE
question: get the label

### ISSUE THREAD

**Issue by Metis77** [derhaeuptling/contao-immobilienscout24-import-bundle#8]
this returns the translated value of the building type. e.g. "Reihenhaus".
`<?= $this->getFormatted($realEstate, 'buildingType') ?>`

this gives me the id of the building type. e.g. "1"
`<?= $realEstate->buildingType ?>`

but how would I get the translated label of the buildingType?
e.g. "Art des Hauses"

would you suggest to do it like this:
`<?= $this->attributes['buildingType'] ?>`

**Comment by m-vo** [comment]
Yes, the attribute list is a mapping `attributeName` &rarr; `label`. 

Of couse you can also use the Contao translator if you prefer this:
```php
<?php echo $this->trans('immoscout24.buildingType'); ?>
```
