### ISSUE TITLE
Meta: Title & Description on Reader 

### ISSUE THREAD

**Issue by Metis77** [derhaeuptling/contao-immobilienscout24-import-bundle#9]

**Comment by m-vo** [comment]
What do you mean by this?

**Comment by Metis77** [comment]
Sorry. 
I meant the Meta Tags in the HTML Head like title and description.

mod_newsreader or mod_event overwrite those, whenever they are implemented.

I did this in the template for now:
```PHP
global $objPage;
$objPage->title = $realEstate->getTitle();
$objPage->description = $this->getFormatted($realEstate, 'descriptionNote');
```

If this solution is ok for you, please just close the issue.

**Comment by m-vo** [comment]
Yeah, I think this should be optional. So if it works, go with your solution I'd say. If this ever needs to be a (configurable) option we can open a new issue.
